Created ArrayList class which implements the List interface.
mate-academy/jv-array-list pull request #1014
Opened 2023-06-29 16:44 UTC by Alex-Solod

2023-06-29 17:00 UTC, Ivan95kos requested changes

2023-07-01 09:46 UTC, Alex-Solod commented on src/main/java/core/basesyntax/ArrayList.java
>      public T remove(int index) {
Can u explain what is <checkIndex(index);> and <checkIndexEqualsSize(index);> ?

2023-07-01 15:06 UTC, Ivan95kos commented on src/main/java/core/basesyntax/ArrayList.java
>      public T remove(int index) {
These are private methods to check the index

```
    private void checkIndex(int index) {
        if (index > size || index < 0) {
            throw new ArrayListIndexOutOfBoundsException("Index is wrong: " + index);
        }
    }

    private void checkIndexEqualsSize(int index) {
        if (index == size) {
            throw new ArrayListIndexOutOfBoundsException("Index is wrong: " + index);
        }
    }
```

2023-07-02 14:27 UTC, Ivan95kos requested changes
please, fix previous comments

2023-07-02 14:27 UTC, Ivan95kos commented on src/main/java/core/basesyntax/ArrayList.java
> +    private Object[] elements;
not fixed, you must use parameterized type `T`

2023-07-02 14:27 UTC, Ivan95kos commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
not fixed

2023-07-02 14:27 UTC, Ivan95kos commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
You use this check several times
```suggestion
        checkIndex(index);
```

2023-07-02 14:27 UTC, Ivan95kos commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
not fixed

2023-07-04 14:13 UTC, closed without merging