crtMthds ArrayList
mate-academy/jv-array-list pull request #1038
Opened 2023-07-10 10:27 UTC by ConfusedSatlan

2023-07-10 14:03 UTC, Dimagaa requested changes

2023-07-11 10:23 UTC, KseniiaMakarova requested changes
code style check failed and your student colleague haven't approved PR

2023-07-11 14:16 UTC, Dimagaa requested changes

2023-07-11 14:22 UTC, Dimagaa approved these changes

2023-07-12 06:06 UTC, KseniiaMakarova requested changes

2023-07-12 06:06 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +    private void increase() {
move all private methods below public

2023-07-12 06:06 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +        final T rmElement = (T) elementArray[index];
bad variable name

2023-07-12 06:06 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +    private int findObject(T object) {
```suggestion
    private int findIndex(T object) {
```

2023-07-12 06:06 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +                || (firstObject != null && firstObject.equals(secondObject));
```suggestion
        return firstObject == secondObject
                || firstObject != null && firstObject.equals(secondObject);
```

2023-07-12 20:48 UTC, nacenik requested changes
Good solution, let's improve it

2023-07-12 20:48 UTC, nacenik commented on src/main/java/core/basesyntax/ArrayList.java
> +    private void increase() {
not fixed.

2023-07-12 20:48 UTC, nacenik commented on src/main/java/core/basesyntax/ArrayList.java
> +
All private methods should be after all publics

2023-07-12 20:48 UTC, nacenik commented on src/main/java/core/basesyntax/ArrayList.java
> +    private static final double INCREASE_SIZE_NUM = 1.5;
```suggestion
    private static final double INCREASE_SIZE_NUMBER = 1.5;
```

2023-07-13 03:25 UTC, nacenik approved these changes
LGTM! 👍

2024-04-22 11:03 UTC, closed without merging