created custom ArrayList
mate-academy/jv-array-list pull request #1054
Opened 2023-07-11 17:41 UTC by IvanFadieiev

2023-07-12 08:25 UTC, SaiyaJ1N approved these changes

2023-07-12 08:25 UTC, SaiyaJ1N commented on src/main/java/core/basesyntax/ArrayList.java
> +    private static final double EMPTY_SIZE = 0;
In my opinion its redudant variable, because you can check isEmpty, by comparing with 0, it`s simplier

2023-07-12 08:38 UTC, AntonZhdanov approved these changes

2023-07-12 13:13 UTC, Vasul-Pankiv requested changes

2023-07-12 13:13 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
use System.arrayCopy()

2023-07-12 13:13 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/ArrayList.java
> +    public void checkIfArrayIsFull() {
```suggestion
    public void growIfArrayFull() {
```

2023-07-12 20:03 UTC, nacenik requested changes
Good solution, let's improve it)

2023-07-13 07:10 UTC, Vasul-Pankiv approved these changes

2026-07-11 10:08 UTC, closed without merging