implements ArrayList with method add(), add(index), addAll(), get(), …
mate-academy/jv-array-list pull request #1079
Opened 2023-08-02 17:56 UTC by mkarmadev

…set(), remove(index), remove(), size(), isEmpty(), checkIndex(), checkIndexForAdd(), growIfArrayFull()

2023-08-02 18:02 UTC, aaananas requested changes

2023-08-02 18:02 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +    private Object[] storage = new Object[DEFAULT_CAPACITY];
see common mistakes

2023-08-02 18:02 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +            storage = Arrays.copyOf(storage, storage.length + (storage.length >> 1));
use System.arrayCopy()

2023-08-03 09:35 UTC, Rommelua approved these changes

2023-08-03 09:35 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +    private int size = 0;
```suggestion
    private int size;
```

2023-08-03 09:35 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        throw new NoSuchElementException("Not found element");
```suggestion
        throw new NoSuchElementException("Not found element " + element );
```

2024-07-08 14:51 UTC, closed without merging