Finished task, try-1.
mate-academy/jv-array-list pull request #1226
Opened 2023-11-20 10:31 UTC by slava-moiseev-kramatorsk

2023-11-20 12:45 UTC, okuzan requested changes
Good job! Read the comments to find out how to improve your code 👇

2023-11-20 12:45 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +    private T[] userArray;
```suggestion
    private T[] values;
```
```suggestion
    private T[] elements;
```
```suggestion
    private T[] data;
```
don't include data type in the variable's name

2023-11-20 12:45 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +    private final int zeroIndex = 0;
remove these fields. 
we can obtain capacity from array

2023-11-20 12:45 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
repeated code,extract to a private method, include index and size in the message. You can hardcode 0 value for zeroIndex

2023-11-20 12:45 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
invert condition, it's better to throw exception early, and unwrap the rest of the code

2023-11-20 12:45 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +            if (element == null && userArray[i] == null
```suggestion
            if (element == userArray[i]
```

2023-11-20 12:45 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
we never need else after throwing, `throws`  exits the method immediately

2023-11-20 12:45 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +            throw new NoSuchElementException("Element not found");
include element in the message

2023-11-20 12:45 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +            int newCapacity = oldCapacity >> 1;
Better replace with simple multiplication for better readability and create a GROW_FACTOR constant

2023-11-20 12:45 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +    private void changeCapacity(int actualCapacity) {
remove argument, you always call it with the same value

2023-11-21 10:29 UTC, Sanderfuck requested changes

2023-11-21 10:29 UTC, Sanderfuck commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
You can use for each loop here

2023-11-21 10:29 UTC, Sanderfuck commented on src/main/java/core/basesyntax/ArrayList.java
> +            }
Grow your array by grow_factor, don`t add every time +1 just use default capacity and clean code after this

2023-11-21 11:04 UTC, slava-moiseev-kramatorsk commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
![image](https://github.com/mate-academy/jv-array-list/assets/94477184/d3ff78e5-f727-4d09-9804-a496167fbb40)
Ні, не можу.

2023-11-21 11:11 UTC, slava-moiseev-kramatorsk commented on src/main/java/core/basesyntax/ArrayList.java
> +            }
Не розумію як обійтись без "+1"  це перевірка на розмір перед додаванням нового єлементу. Замінив на DEFAULT_CAPACITY. Чи малось на увазі  "1" зробити константою щоб було - 
private static final double GROW_FACTOR = 1;
.
.
"int actualCapacity = size + GROW_FACTOR;

2023-11-21 17:38 UTC, okuzan approved these changes
Good job! keep it up 💪

2023-11-21 17:38 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
та, там кастомний ліст, і в нього нема foreach , все ок

2023-11-21 17:38 UTC, okuzan commented on src/main/java/core/basesyntax/ArrayList.java
> +            System.arraycopy(data,0, newElements,0, size);
```suggestion
            System.arraycopy(data, 0, newElements, 0, size);
```
don't forget to autoformat your files before committing with Ctrl Alt L

2023-11-22 08:48 UTC, closed without merging