Implemented custom ArrayList
mate-academy/jv-array-list pull request #1294
Opened 2024-02-14 12:17 UTC by DmitryLazyuka

2024-02-14 12:46 UTC, kozhukhovsky requested changes

2024-02-14 12:46 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ArrayList.java
> +        if (size >= elementData.length) {
move this check to the separate method

2024-02-14 12:46 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ArrayList.java
> +        if (index > size || index < 0) {
move this check for separate method

2024-02-14 12:46 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ArrayList.java
> +        Object[] temp = new Object[elementData.length];
dont need this

2024-02-14 12:46 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ArrayList.java
>      public void addAll(List<T> list) {
use add(value) in loop here

2024-02-14 12:46 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ArrayList.java
> +        if (index < 0 || index >= size) {
move this check to the separate method

2024-02-14 12:46 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ArrayList.java
> +        if (index < 0 || index >= size) {
same for check

2024-02-14 12:46 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ArrayList.java
> +        if (index < 0 || index >= size) {
same for check

2024-02-15 11:42 UTC, Vasul-Pankiv requested changes

2024-02-15 11:42 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/ArrayList.java
> +    }
your method returns true if your index outOfBounds, rename it, method name should represent what it does

2024-02-15 13:01 UTC, kozhukhovsky approved these changes

2026-06-04 07:55 UTC, closed without merging