Solution
mate-academy/jv-array-list pull request #1324
Opened 2024-02-26 20:22 UTC by fedaktaras

Custom Array list created.
Some logic is separated if method is longer than 15 lines.
Some is not.
Tried to write as I understand it.

2024-02-27 10:00 UTC, TonyH277 approved these changes
Nice job! Leave minor comments to improve

2024-02-27 15:00 UTC, andrii-hoienko requested changes
Good job, but some improvements required

2024-02-27 15:00 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/ArrayList.java
> +                elementsArray[i] = list.get(k);
Is it ok that size is not increasing here?

2024-02-27 16:05 UTC, fedaktaras commented on src/main/java/core/basesyntax/ArrayList.java
> +    private void insertInetInExisting(int index, T value) {
Typo (

2024-02-28 08:11 UTC, karma-o commented on src/main/java/core/basesyntax/ArrayList.java
> +    private void insertInetInExisting(int index, T value) {
it is the internet (sorry, couldn't resist 😆)

2024-02-28 08:19 UTC, karma-o approved these changes
Nice! just commented some minor things

2024-02-28 08:19 UTC, karma-o commented on src/main/java/core/basesyntax/ArrayList.java
> +    private Object[] elementsArray;
agree, but Object is fine too, T is more handy to work with tho

2024-02-28 08:19 UTC, karma-o commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
```suggestion
        growIfFull();
```

2025-05-28 09:58 UTC, closed without merging