added solution
mate-academy/jv-array-list pull request #285
Opened 2021-06-10 14:48 UTC by Mzuha

2021-06-10 14:55 UTC, KseniiaMakarova requested changes

2021-06-10 14:55 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
redundant empty line

2021-06-10 14:55 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +    private Object[] storage;
```suggestion
    private T[] storage;
```

2021-06-10 14:55 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +        checkForAdd(index);
let's make the method name more suitable)

2021-06-10 14:55 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +        return (T) storage[index];
```suggestion
        return storage[index];
```

2021-06-10 14:55 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +        T oldValue = (T) storage[index];
```suggestion
        T oldValue = storage[index];
```

2021-06-10 14:55 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +        if (size - 1 > index) {
let's remove this `if`?

2021-06-10 14:55 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +            System.arraycopy(storage, index + 1, storage, index, size - index);
let's think again about the last parameter here

2021-06-10 14:55 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +        throw new NoSuchElementException();
add informative message to exception

2021-06-10 14:55 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +                return oldValue;
can we reuse `remove(int index)`?

2021-06-10 14:55 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +        storage = Arrays.copyOf(storage, newCapacity);
let's use `System.arraycopy()` instead

2021-06-11 05:59 UTC, Mzuha commented
removed redundant lne*

2021-06-11 06:45 UTC, KseniiaMakarova requested changes
good job! added minor comments

2021-06-11 06:45 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
please remove redundant empty line after class declaration

2021-06-11 06:45 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
should we also check capacity here?

2021-06-11 06:45 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/ArrayList.java
> +    private void indexValidation(int index) {
```suggestion
    private void validateIndex(int index) {
```
we should use verbs for method names

2021-06-11 09:17 UTC, KseniiaMakarova approved these changes
great

2022-10-31 12:00 UTC, closed without merging