hw-array-list
mate-academy/jv-array-list pull request #498
Opened 2022-05-30 15:18 UTC by TymurTsvietkov

2022-05-30 19:22 UTC, Zinchuk-Yevhenii-Mate commented on src/main/java/core/basesyntax/ArrayList.java
> +            this.add(list.get(i));
Is it possible not to use the keyword this here?

2022-05-30 19:41 UTC, Zinchuk-Yevhenii-Mate reviewed
Let's improove your code!

2022-05-30 19:41 UTC, Zinchuk-Yevhenii-Mate commented on src/main/java/core/basesyntax/ArrayList.java
> +            if (Objects.equals(array[i],element)) {
Do not use class Objects!!!!!

2022-05-30 19:41 UTC, Zinchuk-Yevhenii-Mate commented on src/main/java/core/basesyntax/ArrayList.java
> +        Object[] newArray = new Object[(int) (array.length * 1.5)];
can we create a constant for this quantity?

2022-05-30 19:41 UTC, Zinchuk-Yevhenii-Mate commented on src/main/java/core/basesyntax/ArrayList.java
> +            this.add(list.get(i));
Is it possible not to use the keyword this here?

2022-05-30 20:02 UTC, Zinchuk-Yevhenii-Mate approved these changes

2022-05-31 06:46 UTC, KostyaNikiforov requested changes

2022-05-31 06:46 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/ArrayList.java
> +    private Object[] array;
```suggestion
    private Object[] values;
```

2022-05-31 06:46 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/ArrayList.java
> +        this.array = new Object[DEFAULT_CAPACITY];
```suggestion
        array = new Object[DEFAULT_CAPACITY];
```

2022-05-31 06:46 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/ArrayList.java
> +    private void sizeCheck() {
Let's add more information about what is going on inside this method

2022-05-31 06:46 UTC, KostyaNikiforov commented on src/main/java/core/basesyntax/ArrayList.java
> +    private void indexCheck(int index) {
```suggestion
    private void validateIndex(int index) {
```

2022-05-31 07:06 UTC, KostyaNikiforov approved these changes
🔥

2025-10-28 15:20 UTC, closed without merging