add solution
mate-academy/jv-array-list pull request #563
Opened 2022-08-07 20:02 UTC by AndrewHudzenko

2022-08-08 09:44 UTC, EagleAndrew requested changes

2022-08-08 09:44 UTC, EagleAndrew commented on src/main/java/core/basesyntax/ArrayList.java
> +            if (Objects.equals(elementData[i], element)) {
if (Objects.equals(elementData[i], element)) {
Don't use Objects
https://mate-academy.github.io/jv-program-common-mistakes/java-core/collections/array-list.html

2022-08-08 09:44 UTC, EagleAndrew commented on src/main/java/core/basesyntax/ArrayList.java
> +            throw new ArrayListIndexOutOfBoundsException("Incorrect index");
```suggestion
            throw new ArrayListIndexOutOfBoundsException("Incorrect index");
            throw new ArrayListIndexOutOfBoundsException("Incorrect index: " + index);
```
Думаю что во всех trow Exception нужно указывать какой именно index, value 
Что-то типа такого

2022-08-08 09:58 UTC, EagleAndrew approved these changes
Excelent)

2022-08-08 15:26 UTC, Sofasmile requested changes

2022-08-08 15:26 UTC, Sofasmile commented on src/main/java/core/basesyntax/ArrayList.java
> +
remove empty line

2022-08-08 15:26 UTC, Sofasmile commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
we can move this check into a private method and call it where needed

2022-08-08 15:26 UTC, Sofasmile commented on src/main/java/core/basesyntax/ArrayList.java
> +                return (T) removObject;
```suggestion
                return remove(i);
```

2022-08-09 06:33 UTC, Sofasmile requested changes

2022-08-09 06:33 UTC, Sofasmile commented on src/main/java/core/basesyntax/ArrayList.java
> +        checkException(index);
```suggestion
        checkIndex(index);
```

2024-04-11 16:42 UTC, closed without merging