Overridden ArrayList methods
mate-academy/jv-array-list pull request #565
Opened 2022-08-08 13:45 UTC by finedefinition

2022-08-08 16:15 UTC, aaananas requested changes
Great job

2022-08-08 16:15 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +    }
```suggestion
    private T[] values;
    private int size;

    public ArrayList() {
        values = (T[]) new Object[DEFAULT_CAPACITY];
    }
```

2022-08-08 16:15 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +        return (T) values[index];
```suggestion
        return values[index];
```

2022-08-08 16:15 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +        T deleteElement = (T) values[index];
```suggestion
        T deleteElement = values[index];
```

2022-08-08 16:15 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +        values[--size] = null;
```suggestion
        size--;
```
not a big deal, but this value will be overwritten anyway, no need to put null there

2022-08-09 18:17 UTC, zachar-chorny approved these changes

2026-07-27 19:36 UTC, closed without merging