methods in custom ArrayList class implemented
mate-academy/jv-array-list pull request #670
Opened 2022-10-12 10:23 UTC by TymurProkhorov

2022-10-12 11:43 UTC, apc10bbe requested changes

2022-10-12 11:43 UTC, apc10bbe commented on src/main/java/core/basesyntax/ArrayList.java
> +        if (index < 0 || index > this.size) {
change  'if (index < 0 || index > this.size)'  to  'if (index < 0 || index >= size)'

2022-10-12 12:19 UTC, apc10bbe requested changes

2022-10-12 12:19 UTC, apc10bbe commented on src/main/java/core/basesyntax/ArrayList.java
> +        if (index < 0 || index >= size) {
here (ONLY ON THIS LINE) '=' not allowed, it will be  'if (index < 0 || index >= size)'

2022-10-12 12:45 UTC, apc10bbe approved these changes

2022-10-12 14:33 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few mistakes 😉

2022-10-12 14:33 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
You can move this conditional to method resize() and avoid code duplicates

2022-10-12 14:33 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
you can use System.arraycopy()

2022-10-12 14:33 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/ArrayList.java
> +            if (Objects.equals(array[i], element)) {
read common mistakes. Don’t  use class Objects

2022-10-13 07:03 UTC, liliia-ponomarenko requested changes
Be attentive to fixing mistakes. Now you have a problem with tests.
<img width="918" alt="image" src="https://user-images.githubusercontent.com/96740815/195525032-12f1a4cc-ded7-4f77-8246-92a7f35461c8.png">

2022-10-13 07:03 UTC, liliia-ponomarenko commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
Do you really need to resize the array when you remove the value?

2022-10-14 09:16 UTC, liliia-ponomarenko approved these changes
good job! 👍

2023-02-25 11:18 UTC, closed without merging