added implementation for the task:
mate-academy/jv-array-list pull request #776
Opened 2023-01-03 10:37 UTC by nikolasdymchenko7

- added constants
- initialization elementData array in the ArrayList constructor
- additional methods: checkIndex(), findIndex(), copyToTempArray(), copyBackToArray(), addElement(), grow(), override method grow(), newCapacity()
- override methods: add(), addAll(), get(), set(), remove(), size(), isEmpty()

2023-01-03 13:02 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-01-03 13:02 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        oldValue = (T) elementData[index];
2 lines?

2023-01-03 13:02 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
```suggestion
        System.arraycopy(elementData, index + 1, elementData, index, size - index);
        elementData[--size] = null;
```

2023-01-03 13:02 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +            if (Objects.equals(elementData[i], element)) {
![image](https://user-images.githubusercontent.com/20326858/210362277-0672f39e-34c8-4b14-8c3b-e73be3745637.png)

2023-01-12 10:18 UTC, aaananas approved these changes

2024-09-19 21:28 UTC, closed without merging