Hw
mate-academy/jv-array-list pull request #803
Opened 2023-01-31 15:27 UTC by IParov

2023-01-31 18:04 UTC, karma-o requested changes

2023-01-31 18:04 UTC, karma-o commented on src/main/java/core/basesyntax/ArrayList.java
> +            }
reuse `remove(int index)` method instead of this

2023-01-31 18:04 UTC, karma-o commented on src/main/java/core/basesyntax/ArrayList.java
> +            throw new NoSuchElementException("No such element exist.");
not informative message

2023-02-01 20:17 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +                elementData.length - (index + 1));
just 1 system.arrayCopy is enough

2023-02-01 20:18 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +        return element;
```suggestion
        for (int i = 0; i < size; i++) {
            if ((element == elementData[i])
                    || (elementData[i] != null && elementData[i].equals(element))) {
                remove(i);
                return true;
            }
        }
        throw new NoSuchElementException("Element: " + element + " is not found.");
```

2023-02-01 20:18 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +        System.arraycopy(updatedData, 0, elementData, 0, size);
```suggestion
        Object[] updatedData = new Object[(int) (elementData.length * CAPACITY_MULTIPLIER)];
        System.arraycopy(elementData, 0, updatedData, 0, size);
        elementData = updatedData;
```

2023-02-02 18:46 UTC, aaananas requested changes

2023-02-02 18:46 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +    private int size = 0;
```suggestion
    private int size;
```

2023-02-02 18:46 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +            }
```suggestion
```

2023-02-02 19:23 UTC, aaananas approved these changes

2024-07-18 12:33 UTC, closed without merging