Implement ArrayList
mate-academy/jv-array-list pull request #899
Opened 2023-03-15 11:01 UTC by fed4ik

2023-03-15 12:45 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-03-15 12:45 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        } else {
```suggestion
            this.elementData = new Object[initialCapacity];
        }  else {
```

2023-03-15 12:45 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        this.elementData = EMPTY_ELEMENTDATA;
![image](https://user-images.githubusercontent.com/20326858/225311731-99829146-32dd-4fe7-a4f9-2fc3c7f7248c.png)

2023-03-15 12:45 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +    private void add(T e, Object[] elementData, int index) {
delete this method

2023-03-15 12:45 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        size = size + 1;
size++

2023-03-15 12:45 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        Object[] elementDataCopy = this.elementData;
delete **s** and **elementDataCopy** 
![image](https://user-images.githubusercontent.com/20326858/225312354-d88d094f-c247-4042-b6db-e28a9e9575b7.png)

2023-03-15 12:45 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        found:
never use labels in you code

2023-03-16 15:42 UTC, aaananas approved these changes

2026-05-14 09:38 UTC, closed without merging