HomeWork-jv-array-list-14-of-april
mate-academy/jv-array-list pull request #923
Opened 2023-04-14 09:48 UTC by ViktoriiaSvidovska

2023-04-14 09:56 UTC, kozhukhovsky requested changes

2023-04-14 09:56 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
Move this to the separate method, like "checkIndex"

2023-04-14 09:56 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ArrayList.java
> +        size += list.size();
```suggestion
        for (int i = 0; i < list.size(); i++) {
            add(list.get(i));
        }
```

2023-04-14 09:56 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ArrayList.java
> +        elements[size - 1] = null;
```suggestion
```

2023-04-17 11:54 UTC, olekskov approved these changes
Good job!

2023-10-18 14:55 UTC, closed without merging