Create ArrayList classe
mate-academy/jv-array-list pull request #925
Opened 2023-04-18 16:51 UTC by inbox-reva

Hi! Please check my solution.

2023-04-18 18:17 UTC, aaananas requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-04-18 18:17 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
remove this outer if-else

2023-04-18 18:17 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +        this.elements = Arrays.copyOf(this.elements, newCapacity);
use system.arraycopy 
![Uploading image.png…]()

2023-04-19 09:30 UTC, Rommelua requested changes
https://mate-academy.github.io/jv-program-common-mistakes/java-core/collections/array-list.html

Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-04-19 09:30 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        this.elements[index] = value;
```suggestion
        elements[index] = value;
```

2023-04-19 09:30 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        System.arraycopy(this.elements, index, this.elements, index + 1, size - index);
Delete all 'this' in all methods

2023-04-19 09:30 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        T[] arrayList = (T[]) new Object[numNew];
numNew, arrayList - what is it? 
![image](https://user-images.githubusercontent.com/20326858/233032082-974b5959-95b7-42f4-bcc5-ceceac9e6928.png)

2023-04-19 09:30 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
![image](https://user-images.githubusercontent.com/20326858/233032543-61f42907-f19b-4c21-bc4d-24c2ad96f24a.png)

2023-04-19 11:21 UTC, Rommelua requested changes
You should fix (or answer to) all mentor's comments before re-request new review. Be attentive and do not hesitate to contact us in Slack if you do not understand something.

2023-04-19 11:21 UTC, Rommelua commented on src/main/java/core/basesyntax/ArrayList.java
> +        }
not fixed

2023-04-19 17:21 UTC, aaananas approved these changes

2023-04-19 17:21 UTC, aaananas commented on src/main/java/core/basesyntax/ArrayList.java
> +        return -1;
```suggestion
        for (int i = 0; i < size; i++) {
            if (element == elements[i] || element != null && element.equals(elements[i]) {
                return i;
            }
        }
        return -1;
```

2023-04-24 08:40 UTC, closed without merging